@echo off
cd /d "%~dp0..\收件箱监听"
chcp 65001 >nul 2>nul
title Inbox Watcher
echo Inbox watcher starting...
echo Watching local artwork folder for new images...
:loop
echo [%time%] 启动收件箱监听...
node inbox-watcher.js
echo [%time%] 监听器退出，3秒后重启...
timeout /t 3 /nobreak >nul
goto loop
